[package]
name = "qgs-test"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
qgs-linux = { path = "../../crates/qgs-linux" }
qgs-audio-pipewire = { path = "../../crates/qgs-audio-pipewire" }
qgs-broadcast-player = { path = "../../crates/qgs-broadcast-player" }
qgs-codec-h264 = { path = "../../crates/qgs-codec-h264" }
qgs-core = { path = "../../crates/qgs-core" }
qgs-h264-422p10 = { path = "../../crates/qgs-h264-422p10" }
qgs-media-runtime = { path = "../../crates/qgs-media-runtime" }
qgs-mp4 = { path = "../../crates/qgs-mp4" }
qgs-mxf = { path = "../../crates/qgs-mxf" }
qgs-protocol = { path = "../../crates/qgs-protocol" }
qgs-software-video = { path = "../../crates/qgs-software-video" }
qgs-vaapi = { path = "../../crates/qgs-vaapi" }
qgs-vulkan = { path = "../../crates/qgs-vulkan" }
sha2 = "0.10"
